# Generated by Django 5.2.11 on 2026-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0002_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('action', models.CharField(max_length=10)),
                ('shares', models.IntegerField(default=0)),
                ('cash', models.FloatField()),
                ('total_assets', models.FloatField()),
                ('roi', models.FloatField()),
            ],
            options={
                'ordering': ['-date', '-roi'],
                'unique_together': {('strategy_name', 'date')},
            },
        ),
    ]
